force-app/main/default/objects/Auteczko__c/Auteczko__c.object-meta.xml
<CustomObject>
    <label>Auteczko</label>
    <nameField>
        <displayFormat>SN{0000}</displayFormat>
        <label>Auteczko Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auteczkos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Auteczko__c/fields/Auteczko_Model__c.field-meta.xml
<CustomField>
    <fullName>Auteczko_Model__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Auteczko Model</label>
    <referenceTo>Auteczko_Model__c</referenceTo>
    <relationshipLabel>Auteczka</relationshipLabel>
    <relationshipName>Auteczka</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Auteczko_Model__c/Auteczko_Model__c.object-meta.xml
<CustomObject>
    <label>Auteczko Model</label>
    <nameField>
        <label>Auteczko Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auteczko Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AuteczkoIterable.cls
global class AuteczkoIterable implements Iterable<Auteczko__c> {    
    private Integer count;
    
    public AuteczkoIterable( Integer count) {
        this.count = count;
    }
    
    public Iterator<Auteczko__c> iterator(){
        List<Auteczko__c> auts = [SELECT Auteczko_Model__c FROM Auteczko__c limit :count];
        List<Auteczko__c> newauts = new List<Auteczko__c>();
        for(Auteczko__c auto : auts){
            Auteczko__c anew = new Auteczko__c(Auteczko_Model__c=auto.Auteczko_Model__c);
            newauts.add(anew);
      }
      return new AuteczkoGenerator(newauts);
   }
}