force-app/main/default/objects/Auteczko__c/Auteczko__c.object-meta.xml
<CustomObject>
    <label>Auteczko</label>
    <nameField>
        <displayFormat>SN{0000}</displayFormat>
        <label>Auteczko Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auteczkos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Auteczko__c/fields/Auteczko_Model__c.field-meta.xml
<CustomField>
    <fullName>Auteczko_Model__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Auteczko Model</label>
    <referenceTo>Auteczko_Model__c</referenceTo>
    <relationshipLabel>Auteczka</relationshipLabel>
    <relationshipName>Auteczka</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Auteczko_Model__c/Auteczko_Model__c.object-meta.xml
<CustomObject>
    <label>Auteczko Model</label>
    <nameField>
        <label>Auteczko Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auteczko Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AuteczkoBatch.cls
global class AuteczkoBatch implements Database.Batchable<sObject>, Database.Stateful {
    public Integer recordsProcessed = 0;
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        // collect the batches of records or objects to be passed to execute         
        String query = 'SELECT Name FROM Auteczko_Model__c limit 10'  ;         
        return Database.getQueryLocator(query);       
    }
    
    global void execute(Database.BatchableContext BC, List<Auteczko_Model__c> scope) {
        List<Auteczko__c> autList = new List<Auteczko__c>();
        // process each batch of records
        for(Auteczko_Model__c model:scope){
              for (integer i=0;i<25;i++)
              {
                    Auteczko__c anew= new Auteczko__c(Auteczko_Model__c=model.Name);
                    autList.add(anew);
              }
        }
        try {
            insert autList;
        } 
        catch(Exception e) {
            System.debug(e);
        }
         
    }        

    public void finish(Database.BatchableContext bc){
		// execute any post-processing operations
    }
}