force-app/main/default/objects/Wheel__c/Wheel__c.object-meta.xml
<CustomObject>
    <label>Wheel</label>
    <nameField>
        <displayFormat>WID{0000}</displayFormat>
        <label>Wheel Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wheels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Wheel__c/fields/AuteczkoID__c.field-meta.xml
<CustomField>
    <fullName>AuteczkoID__c</fullName>
    <label>AuteczkoID</label>
    <referenceTo>Auteczko__c</referenceTo>
    <relationshipLabel>Wheels</relationshipLabel>
    <relationshipName>Wheels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Wheel__c/fields/Position_Front_Back__c.field-meta.xml
<CustomField>
    <fullName>Position_Front_Back__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Position Front/Back</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Wheel__c/fields/Position_Right_Left__c.field-meta.xml
<CustomField>
    <fullName>Position_Right_Left__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Position Right/Left</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/WheelTriggerHandler.cls
public class WheelTriggerHandler {
    public static void TriggerHandler(Wheel__c [] triggerNew){
        List<Id> auts=new List<Id>();
        for (Wheel__c w : triggerNew) {
            auts.add(w.AuteczkoID__c);
        }
        
        List<Wheel__c> allWheels = new List<Wheel__c>(
            [SELECT Name, AuteczkoID__c, Position_Front_Back__c, Position_Right_Left__c
             FROM Wheel__c
             WHERE AuteczkoID__c IN :auts]);
        
        Map<Id,List<Wheel__c>> aWheels=new Map<Id,List<Wheel__c>>();
        for (Wheel__c wheel : allWheels) {
            if (aWheels.containsKey(wheel.AuteczkoId__c)) {
                aWheels.get(wheel.AuteczkoId__c).add(wheel);
            }
            else{
                List<Wheel__c> w=new List<Wheel__c>();
                w.add(wheel);
                aWheels.put(wheel.AuteczkoId__c,w);
            }
        }
            
        for (Wheel__c wheel : triggerNew) {
            List<Wheel__c> currentWheels=aWheels.get(wheel.AuteczkoID__c);
            if (currentWheels != null) {
                for (Wheel__c cw : currentWheels) {
                    if (cw.Position_Front_Back__c == wheel.Position_Front_Back__c && cw.Position_Right_Left__c == wheel.Position_Right_Left__c) {
                        wheel.AuteczkoID__c.addError('To auteczko ma już przypisaną oponę na tym miejscu!');
                    }
                }
            }
        }
    }
}